version: '3.8'

services:
  indexing-api-app:
    build: .
    container_name: indexing-api-app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    environment:
      GOOGLE_SERVICE_ACCOUNT_PATH: ${GOOGLE_SERVICE_ACCOUNT_PATH}
    restart: unless-stopped
